# 违禁词列表
bad-words:
  - "L"
  - "l"
  - "FW"
  - "FV"
  - "SB"
  - "cnm"
  - "sb"
  - "NMSL"
  - "LLL"
  - "傻逼"
  - "废物"
  - "LOL"
  - "FVV"
  - "FV"
  - "2B"
  - "臭"
  - "日"
  - "艹你妈"
  - "艹"
  - "操"

# 禁言阈值
mute-threshold: 3