name: Lengbanlist
main: org.leng.Lengbanlist
version: 1.7.2
api-version: 1.21
commands:
  lban:
    description: 主命令
    usage: /<command> <subcommand>
  ban:
    description: 封禁玩家
    usage: /<command> <player> <days> <reason>
  ban-ip:
    description: 封禁 IP
    usage: /<command> <IP> <days> <reason>
  unban:
    description: 解封玩家
    usage: /<command> <player>
  warn:
    description: 警告玩家
    usage: /<command> <player> <reason>
  unwarn:
    description: 移除警告
    usage: /<command> <player>
  check:
    description: 检查玩家或 IP 的封禁状态
    usage: /<command> <player/IP>
  language:
    description: 切换语言
    usage: /<command>
  report:
    description: 举报玩家
    usage: /<command> <player> <reason>
  admin:
    description: 管理举报
    usage: /<command> <subcommand>
  info:
    description: 显示插件信息
    usage: /<command>
  kick:
    description: 踢出玩家
    usage: /<command> <玩家名> [原因]