name: Lengbanlist
main: org.leng.Lengbanlist
version: ${project.version}
api-version: 1.21
folia-supported: true
authors: 
  - LengMC
  - xiaoshaziYA
  - ShaoqingG
  - OpenSource
description: qwq
commands:
  lban:
    description: 主命令
    usage: /<command> <subcommand>
  ban:
    description: 封禁玩家
    usage: /<command> <玩家名> <时间/auto> <理由>
    permission: lengbanlist.ban
  ban-ip:
    description: 封禁 IP
    usage: /<command> <IP> <时间/auto> <理由>
    permission: lengbanlist.banip
  unban:
    description: 解封玩家
    usage: /<command> <玩家名/IP>
    permission: lengbanlist.unban
  warn:
    description: 警告玩家
    usage: /<command> <玩家名> <理由>
    permission: lengbanlist.warn
  unwarn:
    description: 移除警告
    usage: /<command> <玩家名> [警告ID]
    permission: lengbanlist.unwarn
  check:
    description: 检查玩家或 IP 的封禁状态
    usage: /<command> <玩家名/IP>
    permission: lengbanlist.check
  language:
    description: 切换语言
    usage: /<command>
    permission: lengbanlist.language
  report:
    description: 举报玩家
    usage: /<command> <玩家名> <理由>
    permission: lengbanlist.report
  admin:
    description: 管理举报
    usage: /<command> <子命令>
    permission: lengbanlist.admin
  info:
    description: 显示插件信息
    usage: /<command>
    permission: lengbanlist.info
  kick:
    description: 踢出玩家
    usage: /<command> <玩家名> [理由]
    permission: lengbanlist.kick
  allowmsg:
    description: 允许玩家发送消息
    usage: /<command> <玩家名>
    permission: lengbanlist.allowmsg
  warnmsg:
    description: 警告玩家发送违规消息
    usage: /<command> <玩家名>
    permission: lengbanlist.warnmsg
  setban:
    description: 设置玩家的封禁时间
    usage: /<command> <玩家名/IP> <时间/forever/auto> <理由>
    permission: lengbanlist.setban
permissions:
  lengbanlist.ban:
    description: 允许使用封禁玩家命令
    default: op
  lengbanlist.banip:
    description: 允许使用封禁 IP 命令
    default: op
  lengbanlist.unban:
    description: 允许使用解封玩家命令
    default: op
  lengbanlist.warn:
    description: 允许使用警告玩家命令
    default: op
  lengbanlist.unwarn:
    description: 允许使用移除警告命令
    default: op
  lengbanlist.check:
    description: 允许使用检查封禁状态命令
    default: op
  lengbanlist.language:
    description: 允许使用切换语言命令
    default: op
  lengbanlist.report:
    description: 允许使用举报玩家命令
    default: true
  lengbanlist.admin:
    description: 允许使用管理举报命令
    default: op
  lengbanlist.info:
    description: 允许使用显示插件信息命令
    default: op
  lengbanlist.kick:
    description: 允许使用踢出玩家命令
    default: op
  lengbanlist.allowmsg:
    description: 允许使用允许玩家发送消息命令
    default: op
  lengbanlist.warnmsg:
    description: 允许使用警告玩家发送违规消息命令
    default: op
  lengbanlist.setban:
    description: 允许使用设置封禁时间命令
    default: op